version: "3"

services:
  main:
    build:
      dockerfile: ./.docker/Dockerfile
      context: ./
    container_name: buckit
    volumes:
      - ./service:/service
      - ./web:/web
    ports:
      - "80:8080"
      - "3001:3001"
    networks:
      - backend
    command: gin -i -a 3000 -p 8080 -b ./out/gin-bin run .