version: "3"

services:
  app:
    build: .
    restart: always
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app
    ports:
      - 80:3000
    command: ["gin","--appPort","8080","run","app.go"]