version: "3"

services:
  app:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/go/src/github.com/theclocker/buckit
#    working_dir: /go/src/github.com/theclocker/buckit
#    ports:
#      - 80:3000
    #command: ["gin","--appPort","8080","run","main.go"]